- pom.xml
- src/main/java/it/reply/orchestrator/service/deployment/providers/ImServiceImpl.java
Small fixes to adapt the new exceptions thrown by the im-java-api and to remove the calls to deprecated methods.
> Adapt to the new im-java-api code

- restdocs/index.html
- src/main/java/it/reply/orchestrator/controller/ResourceController.java
- src/main/java/it/reply/orchestrator/service/DeploymentServiceImpl.java
- src/test/java/it/reply/orchestrator/controller/DeploymentControllerTest.java
- src/test/resources/data/database-init-pagination.xml
- src/test/resources/data/database-init.xml
> Fix "output" field value in the test.

- pom.xml
- src/main/java/it/reply/orchestrator/service/deployment/providers/ImServiceImpl.java
- src/test/java/it/reply/orchestrator/controller/DeploymentControllerTest.java
- src/test/java/it/reply/orchestrator/controller/TemplateControllerTest.java
- src/test/java/it/reply/orchestrator/service/TOSCAServiceTest.java
Update some method calls to comply with the google codestyle.
Update FileIO functions.
Update pom.xml with the new im-java-api version.
> Code adapted to the updated im-java-api functions and codestyle

- src/main/java/it/reply/orchestrator/config/security/WebSecurityConfig.java
> Allow info path to be accessed without authentication

- src/main/java/it/reply/orchestrator/service/commands/GetSlam.java
> Support multiple SLAs for cloud providers

- src/main/java/it/reply/orchestrator/controller/DeploymentController.java
- src/main/java/it/reply/orchestrator/controller/ResourceController.java
- src/main/java/it/reply/orchestrator/dal/entity/AbstractResourceEntity.java
- src/main/java/it/reply/orchestrator/dal/entity/Deployment.java
- src/main/java/it/reply/orchestrator/dal/entity/Resource.java
- src/test/java/it/reply/orchestrator/controller/ControllerTestUtils.java
- src/test/java/it/reply/orchestrator/controller/DeploymentControllerTest.java
- src/test/java/it/reply/orchestrator/controller/ResourceControllerTest.java
- src/test/java/it/reply/orchestrator/service/DeploymentServiceTest.java
- src/test/java/it/reply/orchestrator/service/deployment/providers/ImServiceTest.java
> Sort REST resources by creation date

- src/main/java/it/reply/orchestrator/config/security/WebSecurityConfig.java
- src/main/java/it/reply/orchestrator/service/security/UserInfoIntrospectingTokenService.java
Added check for openid scope before asking data to user info endpoint
Added check if access token has openid scope in security filter
Resolves #81
> Add checks for openid scope

- src/main/java/it/reply/orchestrator/service/commands/BaseDeployCommand.java
- src/main/java/it/reply/orchestrator/service/commands/BaseRankCloudProvidersCommand.java
- src/main/java/it/reply/orchestrator/service/commands/Deploy.java
- src/main/java/it/reply/orchestrator/service/commands/GetCmdbDataDeploy.java
- src/main/java/it/reply/orchestrator/service/commands/GetCmdbDataUpdate.java
- src/main/java/it/reply/orchestrator/service/commands/GetMonitoringData.java
- src/main/java/it/reply/orchestrator/service/commands/GetOneDataData.java
- src/main/java/it/reply/orchestrator/service/commands/GetProvidersRank.java
- src/main/java/it/reply/orchestrator/service/commands/GetSlam.java
- src/main/java/it/reply/orchestrator/service/commands/Notify.java
- src/main/java/it/reply/orchestrator/service/commands/PollDeploy.java
- src/main/java/it/reply/orchestrator/service/commands/PollUndeploy.java
- src/main/java/it/reply/orchestrator/service/commands/PrefilterCloudProviders.java
- src/main/java/it/reply/orchestrator/service/commands/Undeploy.java
- src/main/java/it/reply/orchestrator/service/commands/Update.java
- src/main/java/it/reply/orchestrator/service/commands/chronos/DeployOnChronos.java
- src/main/java/it/reply/orchestrator/service/commands/chronos/PollDeployOnChronos.java
- src/main/java/it/reply/orchestrator/service/commands/chronos/UndeployOnChronos.java
- src/main/java/it/reply/orchestrator/service/deployment/providers/DeploymentStatusHelper.java
- src/main/java/it/reply/orchestrator/service/deployment/providers/DeploymentStatusHelperImpl.java
> Improve error reason message in REST response

- pom.xml
- src/main/resources/tosca-definitions/normative-types.yml
> Support TOSCA extended node requirements

- src/main/java/it/reply/orchestrator/service/IndigoInputsPreProcessorService.java
> Support input substitution in listValue properties

- src/main/resources/tosca-definitions/custom_types.yaml
See https://github.com/indigo-dc/tosca-types/blob/master/custom_types.yaml
> Update TOSCA custom_types to latest development version

- src/main/java/it/reply/orchestrator/config/security/WebSecurityConfig.java
- src/main/java/it/reply/orchestrator/service/security/UserInfoIntrospectingTokenService.java
> Check access token expiration date and signature

- src/main/resources/monitoring/monitoring.properties
> Update default monitoring endpoint

- src/main/resources/tosca-definitions/custom_types.yaml
> Update custom INDIGO TOSCA types

- src/main/resources/tosca-definitions/custom_types.yaml
> Update TOSCA INDIGO custom types

- src/main/java/it/reply/orchestrator/service/ToscaService.java
- src/main/java/it/reply/orchestrator/service/ToscaServiceImpl.java
- src/main/java/it/reply/orchestrator/service/deployment/providers/ImServiceImpl.java
- src/main/java/it/reply/orchestrator/service/security/OAuth2TokenService.java
> Send the client credential to CLUES through TOSCA template

- src/test/java/it/reply/orchestrator/service/CmdbServiceIT.java
- src/test/java/it/reply/orchestrator/service/SlamServiceIT.java
The integration endpoints are not reachable anymore
> TMP disable failing integration tests

- Jenkinsfile
++ Usual CI and metrics checks 
++ Docker image building and publication to DockerHub
++ OWASP dependency check
++ Issue creation on JIRA when new release (tag) is pushed
> Jenkins pipeline for orchestrator

- src/main/resources/db/changelog/0003_orchestrator-mysql-timestamp-default-value-2101.yaml
- src/main/resources/db/changelog/db.orchestrator.changelog-master.yaml
> Drop ON UPDATE CURRENT_TIMESTAMP(6) from non-null TIMESTAMP columns

- Jenkinsfile
This commit:
- Switch the tags & branches selector from regex to ANT style patterns since jenkins doesn't support the former in declarative pipelines
- Extracts the project version with a maven command and use it as docker image tag
> Fix ANT pattern & tag version

- tools/monitoring-probes/README.md
- tools/monitoring-probes/health-check.sh
Added a script that sends a request to the /info endpoint.
Refers to issue #309
> Added first simple probe

- src/main/java/it/reply/orchestrator/config/IgniteConfig.java
- src/main/java/it/reply/orchestrator/config/properties/OrchestratorProperties.java
> Disable Ignite AutoDiscovery for non clustered mode

- pom.xml
- src/main/java/it/reply/orchestrator/controller/ConfigurationEndpoint.java
- src/main/java/it/reply/orchestrator/controller/MiscController.java
- src/main/java/it/reply/orchestrator/dto/SystemEndpoints.java
- src/main/java/it/reply/orchestrator/service/ConfigurationService.java
- src/main/java/it/reply/orchestrator/service/ConfigurationServiceImpl.java
- src/main/java/it/reply/orchestrator/service/VaultServiceImpl.java
- src/main/resources/application.properties
- src/main/resources/tosca-definitions/custom_types.yaml
- src/test/java/it/reply/orchestrator/controller/MiscControllerIT.java
- src/test/java/it/reply/orchestrator/service/ConfigurationServiceTest.java
- src/test/java/it/reply/orchestrator/service/VaultServiceTest.java
Added /configuration endpoint in orchestrator to retrieve urls for dashboard configuration;  Changed Vault endpoint configuration
> Added /configuration endpoint

- src/main/java/it/reply/orchestrator/dto/cmdb/ChronosService.java
- src/main/java/it/reply/orchestrator/dto/cmdb/CloudService.java
- src/main/java/it/reply/orchestrator/dto/cmdb/ComputeService.java
- src/main/java/it/reply/orchestrator/dto/cmdb/MarathonService.java
- src/main/java/it/reply/orchestrator/dto/cmdb/MesosFrameworkService.java
- src/main/java/it/reply/orchestrator/dto/cmdb/QcgService.java
- src/main/java/it/reply/orchestrator/dto/ranker/MonitoringService.java
- src/main/java/it/reply/orchestrator/service/commands/GetProvidersRank.java
Fixes #368
(cherry picked from commit 87d2c60594e851d83f02e349e8c22183a7949f2f)
> Fix ParentServiceId not populated in CPR requests (CP)

- README.md
Added Acknowledgments in README
> Added Acknowledgments

- pom.xml
- Update Alien4Cloud version to 2.1.0-DEEP-1.2.1
> Update alien4cloud version

- src/main/java/it/reply/orchestrator/service/ToscaService.java
- src/main/java/it/reply/orchestrator/service/ToscaServiceImpl.java
- src/main/java/it/reply/orchestrator/service/deployment/providers/ImServiceImpl.java
- src/main/java/it/reply/orchestrator/service/deployment/providers/MarathonServiceImpl.java
- src/main/java/it/reply/orchestrator/utils/ToscaConstants.java
- src/test/java/it/reply/orchestrator/service/ToscaServiceTest.java
- src/test/java/it/reply/orchestrator/service/deployment/providers/MarathonServiceTest.java
- src/test/java/it/reply/orchestrator/util/TestUtil.java
- src/test/resources/tosca/marathon_app.json
Fixed network definition on isolated private network type
> Hybrid update reloaded
